name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo, pdo_mysql
          ini-values: post_max_size=256M, upload_max_filesize=256M

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Copy env
        run: cp .env.example .env

      - name: Run tests
        run: vendor/bin/phpunit

      # Opsional: Deploy ke server (seperti ke FTP, SSH, atau layanan cloud)
      # - name: Deploy to production
      #   run: echo "Deploy step here"