# Docker Compose untuk Single Environment di VPS dengan aaPanel
version: '3.8'

services:
  # Nginx Web Server
  nginx-demo:
    image: nginx:alpine
    container_name: nginx-demo-ci4api
    ports:
      - "8081:80"  # Sesuai dengan port Cloudflare tunnel
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/demo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm-demo
    networks:
      - demo-network
    restart: unless-stopped

  # PHP-FPM
  php-fpm-demo:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: production
    container_name: php-fpm-demo-ci4api
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.production.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql-demo
      - redis-demo
    networks:
      - demo-network
    restart: unless-stopped
    environment:
      - CI_ENVIRONMENT=production

  # MySQL Database
  mysql-demo:
    image: mysql:8.0
    container_name: mysql-demo-ci4api
    ports:
      - "3309:3306"  # Avoid conflict dengan MySQL di port 3306 & 3308
    volumes:
      - mysql-demo-data:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - demo-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  # Redis Cache
  redis-demo:
    image: redis:alpine
    container_name: redis-demo-ci4api
    ports:
      - "6382:6379"  # Avoid conflict dengan Redis di port 6379 & 6381
    volumes:
      - redis-demo-data:/data
    networks:
      - demo-network
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

volumes:
  mysql-demo-data:
  redis-demo-data:

networks:
  demo-network:
    driver: bridge
